<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use App\Models\Contact;
use App\Models\Conversation;
use App\Models\Store;
use App\Models\WidgetSession;
use App\Services\Ai\AgentOrchestrator;
use App\Services\Whatsapp\WhatsappManager;
use App\Services\Whatsapp\WhatsappSender;
use Illuminate\Http\Request;

/**
 * Public conversational endpoint used by the chat widget. Serves a fresh
 * customer without requiring a WhatsApp number; replies are generated by the
 * AI agent and returned as JSON for the widget to display.
 */
class AgentApiController extends Controller
{
    public function __construct(
        protected AgentOrchestrator $agent,
        protected WhatsappSender $sender,
        protected WhatsappManager $whatsapp,
    ) {
    }

    public function message(Request $request)
    {
        $shop = $request->input('shop');
        $store = $shop ? Store::where('myshopify_domain', $shop)->first() : null;

        if (! $store || ! $store->agentConfig?->enabled) {
            return response()->json(['error' => 'Agent disabled'], 409);
        }

        $data = $request->validate([
            'message' => ['required', 'string', 'max:2000'],
            'session_key' => ['nullable', 'string'],
            'history' => ['nullable', 'array'],
        ]);

        $session = WidgetSession::where('store_id', $store->id)
            ->where('session_key', $data['session_key'] ?? '')
            ->latest('last_active_at')->first();

        $contact = $session?->contact;

        $response = $this->agent->respond(
            $store,
            $data['message'],
            $contact,
            conversation: null,
            history: $data['history'] ?? [],
        );

        return response()->json([
            'reply' => $response['content'],
            'confidence' => $response['confidence'],
            'escalated' => $response['escalated'],
            'tool_calls' => $response['tool_calls'],
        ]);
    }
}
